version: '3.8'
services:
  odoo:
    image: odoo:16.0
    restart: always
    depends_on:
      - db
    ports:
      - "80:8069"
  db:
    image: postgres:15
    restart: always
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=odoo
      - POSTGRES_USER=odoo