version: '3.8'
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    domainname: udistritalredescorporativas.lan
    container_name: mailserver
    hostname: mail
    restart: always
    ports:
      - "25:25"
      - "587:587"
      - "465:465"
    volumes:
      - './storage/mail-server/certs/:/tmp/dms/custom-certs/'
      - './storage/mail-server/dms/mail-data/:/var/mail/'
      - './storage/mail-server/dms/mail-state/:/var/mail-state/'
      - './storage/mail-server/dms/mail-logs/:/var/log/mail/'
      - './storage/mail-server/dms/config/:/tmp/docker-mailserver/'
    environment:
      - ENABLE_FAIL2BAN=1
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/tmp/dms/custom-certs/public.crt
      - SSL_KEY_PATH=/tmp/dms/custom-certs/private.key
      - ONE_DIR=1
      - ENABLE_POSTGREY=0
      - ENABLE_CLAMAV=0
      - ENABLE_SPAMASSASSIN=0
      - SPOOF_PROTECTION=0
      - ACCOUNT_PROVISIONER=LDAP
      # ldap
      - LDAP_SERVER_HOST=freeipa.udistritalredescorporativas.lan
      - LDAP_BIND_DN=uid=admin,cn=users,cn=compat,dc=udistritalredescorporativas,dc=lan
      - LDAP_BIND_PW=freeipaserver
      - LDAP_SEARCH_BASE=dc=udistritalredescorporativas,dc=lan
      - LDAP_QUERY_FILTER_DOMAIN=(&(|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s)))
      - LDAP_QUERY_FILTER_USER=(&(mail=%s))
      - LDAP_QUERY_FILTER_ALIAS=(&(mailAlias=%s))
      - LDAP_QUERY_FILTER_GROUP=(&(mailGroupMember=%s))
      - LDAP_QUERY_FILTER_SENDERS=
      - SPOOF_PROTECTION=1
      - PERMIT_DOCKER=host
    cap_add:
      - NET_ADMIN # For Fail2Ban to work
      - SYS_PTRACE