version: '3.7'
services:
  freeipa:
    image: freeipa/freeipa-server:fedora-37-4.10.1
    restart: unless-stopped
    hostname: udistrital.redescorporativas.local
    environment:
      IPA_SERVER_HOSTNAME: udistrital.redescorporativas.local
      TZ: "America/Bogota"
    tty: true
    stdin_open: true
    user: root
    cap_add:
      - ALL
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/lib/ipa-data:/data:ro
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    security_opt:
      - "seccomp:unconfined"
    command:
      - -U
      - --domain=redescorporativas.local
      - --realm=redescorporativas.local
      - --http-pin=YOURPASSWORD
      - --dirsrv-pin=YOURPASSWORDe
      - --ds-password=YOURPASSWORD
      - --admin-password=YOURPASSWORD
      - --no-host-dns
      - --unattended
      - --cgroupns host
    ports:
      - "80:80"
      - "443:443"
      - "389:389"
      - "636:636"
      - "88:88"
      - "464:464"
      - "88:88/udp"
      - "464:464/udp"
      - "123:123/udp"
      - "7389:7389"
      - "9443:9443"
      - "9444:9444"
      - "9445:9445"