version: "3.8"
services:  
  freeipa:
    image: freeipa/freeipa-server:centos-7
    hostname: udistritalredescorporativas
    domainname: udistritalredescorporativas.local
    container_name: freeipa-dev
    ports:
      - 80:80
      - 443:443
      - 389:389
      - 636:636
      - 88:88
      - 464:464
      - 88:88/udp
      - 464:464/udp
      - 123:123/udp
    dns:
      - 10.0.2.1
      - 1.1.1.1
    restart: unless-stopped
    tty: true
    stdin_open: true
    environment:
      IPA_SERVER_HOSTNAME: freeipa.udistritalredescorporativas.local
      IPA_SERVER_IP: 10.0.2.11
      TZ: "America/Bogota"
    command:
      - -U
      - --domain=udistritalredescorporativas.local
      - --realm=udistritalredescorporativas.local
      - --admin-password=freeipaserver
      - --http-pin=freeipaserver
      - --dirsrv-pin=freeipaserver
      - --ds-password=freeipaserver
      - --no-dnssec-validation
      - --no-host-dns
      - --setup-dns
      - --auto-forwarders
      - --allow-zone-overlap
      - --unattended
    cap_add:
      - SYS_TIME
      - NET_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - ./data:/data
      - ./logs:/var/logs
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.lo.disable_ipv6=0
    security_opt:
      - "seccomp:unconfined"
    labels:
      - dev
